<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(UseStubs)' == 'true'">
    <DefineConstants>$(DefineConstants);MELONLOADER_STUBS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MegabonkDir)' == ''">
    <MegabonkDir>Z:\SteamLibrary\steamapps\common\Megabonk</MegabonkDir>
  </PropertyGroup>

  <ItemGroup Condition="'$(UseStubs)' != 'true'">
    <Reference Include="MelonLoader">
      <HintPath>$(MegabonkDir)\MelonLoader\net6\MelonLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>$(MegabonkDir)\MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(MegabonkDir)\MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(MegabonkDir)\MelonLoader\Il2CppAssemblies\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(MegabonkDir)\MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(MegabonkDir)\MelonLoader\Il2CppAssemblies\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
